### ISSUE TITLE
Debug LEDs for the RX and TX UART controller

### ISSUE THREAD

**Issue by mitch-gilmore** [BostonUniversitySeniorDesign/brain-4ce#4]
Currently the LEDs never turn on when sending serial information to and from the MCU. I suspect this is because insufficient current is passing through the device. In order to debug I purpose to first connect jumpers to the pull down resistors in order to view that the UART controller is falling low periodically when sending '?' over serial which requests all the registers in the ADC to be read out. If the probes are placed at the nodes between the resistors and the LED it should also allow for the current though the LED to determined.
![image](https://user-images.githubusercontent.com/102109623/227747535-ea32c876-02e6-4e13-a31d-982112ae85f5.png)

**Comment by atjohnson** [comment]
Hey @mgilmore42,

I measured the voltage at both nodes circled in the picture relative to ground and found them to be high at all times no matter what command is sent to the board. I'm getting roughly 3.191V at the VDD node and 3.165V at the D10 and D11 nodes.

**Comment by mitch-gilmore** [comment]
@atjohnson Did you use an oscilloscope or the DMM?

**Comment by atjohnson** [comment]
@mgilmore42 DMM. Should I try the oscilloscope too?

**Comment by mitch-gilmore** [comment]
@atjohnson generally speaking the DMM is ill suited for looking at transient signals. You should look at it with an oscilloscope.

**Comment by mitch-gilmore** [comment]
For traceability the problem was solved by editing the firmware of the UART controller. By default the GPIO pins default to inputs and do not flash the LEDs (see [datasheet here](https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf#unique_28)). This needed to be enabled in the controller firmware. This was accomplished by using [Simplicity Studio](https://www.silabs.com/developers/simplicity-studio) and in the _Xpress Configurator_ setting the GPIO pins 1 and 2 to their alternate functionality. @atjohnson can you provide a screenshot to aid others if they use our work later on?

**Comment by atjohnson** [comment]
The GPIO0 and GPIO1 signals were changed from an Alternate Function of "GPIO" to "TX Toggle" and "RX Toggle" respectively:
![GPIO Config](https://user-images.githubusercontent.com/75290142/227805672-a9a2dcd0-7f6f-4326-af84-172bca6844b4.jpg)
